[features]
seeds = false
[programs.localnet]
daddy_staking_contract = "A4RDTZxpskjCkY9mWgkovkx5aXUYEwZHJkQ6uWi1nWWH"

[programs.devnet]
daddy_staking_contract = "A4RDTZxpskjCkY9mWgkovkx5aXUYEwZHJkQ6uWi1nWWH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
